[package]
name = "2016-08-29-about-bases"
description = "https://www.reddit.com/r/dailyprogrammer/comments/504rdh"
version = "0.1.0"
authors = ["Martin Thurau <martin.thurau@gmail.com>"]

[dependencies]
